# Generated by Django 4.2.2 on 2023-06-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_cart_category_product_cartitem_cart_products_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
