# Generated by Django 4.2.2 on 2023-06-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_remove_category_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
