# Generated by Django 4.2.2 on 2023-06-28 04:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_rename_images_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="images",
        ),
    ]
