# Generated by Django 4.2.2 on 2023-06-28 04:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_rename_image_product_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="images",
            new_name="image",
        ),
    ]
