# Generated by Django 4.2.2 on 2023-06-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_rename_images_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
