# Generated by Django 4.2.2 on 2023-06-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_image_remove_product_image_product_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="shop/static/shop/images/")),
            ],
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(blank=True, to="shop.images"),
        ),
    ]
