# Generated by Django 4.2.2 on 2023-06-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_remove_product_images_images_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="picture",
            field=models.ImageField(upload_to="products"),
        ),
    ]
