# Generated by Django 4.2.2 on 2023-06-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_alter_images_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category_banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="products/category_banner")),
            ],
        ),
    ]
