# Generated by Django 4.2.2 on 2023-06-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_category_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="category_banner",
            name="category_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="category_banner",
            name="picture",
            field=models.ImageField(upload_to="category_banner"),
        ),
    ]
