# Generated by Django 4.2.2 on 2023-06-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0017_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
