# Generated by Django 4.2 on 2023-07-04 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0018_alter_product_name_subcategory_product_subcategory"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Watchlist",
            new_name="Wishlist",
        ),
    ]
