# Generated by Django 4.2 on 2023-07-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0019_rename_watchlist_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
