# Generated by Django 4.2 on 2023-07-04 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0020_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
